---
name: "[BETA] Tailscale"
version: 0.9.0.5-rc01
slug: tailscale-beta
description: "[BETA] Zero config VPN for building secure networks"
url: https://github.com/lmagyar/homeassistant-addon-tailscale-beta
codenotary: lmagyar1973@gmail.com
ingress: true
ingress_port: 0
ingress_stream: true
startup: services
panel_icon: mdi:vpn
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
hassio_api: true
host_network: true
ports:
  1080/tcp: 1080
schema:
  tags: ["match(^tag:[a-zA-Z0-9]-?[a-zA-Z0-9]+$)?"]
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/lmagyar/{arch}-addon-tailscale-beta
